#ifndef XANTHUS_SYSTEM_INTENT_HPP
#define XANTHUS_SYSTEM_INTENT_HPP

#include "entity/Entity.hpp"

#include "intent/Intent.hpp"

#include <cstdint>
#include <memory>
#include <set>

namespace xanthus
{
namespace system
{

/** Processes all intents generated by entities */
class Intent
{
public:
    struct Order
    {
        bool operator<(Order const& other) const
        {
            return priority < other.priority;
        }

        uint16_t priority;
        entity::Entity entity;
        std::shared_ptr<intent::Intent> intent;
    };

    Intent(WorldTime& worldTime);
    ~Intent() = default;

    void Register(Order order);
    void Process();

private:
    WorldTime& m_worldTime;

    std::set<Order> m_queue;
};

}
}

#endif // XANTHUS_SYSTEM_INTENT_HPP
